# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b88d5548e8e17b1d32f92e1224144a7d35e32fda8fe07d14d747b20ac1b73cfb8889430162479ad819d030d3e55dedb21f2cdca1a207a09feaa7f849d79e130

test:
  secret_key_base: 5cb2a2685f6cd7f221eeb6267bc10810d59cae45e43b4ee2612033c21ebbd138fa023da1491ca242ab7700b6836e6f3835552572a42ee3ed1c094d39dd060c26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
